- name: Setup RSyslog for remote logging
  ansible.builtin.copy:
    src: ../templates/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
  become: yes
  become_user: root
  notify:
    - Restart Rsyslog
 
  
