---
- name: Copy K3s service file
  template:
    src: "node.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify: Reload K3s node service

- name: Enable K3s service
  systemd:
    name: k3s-node
    state: started
    enabled: yes
